"""rec-catalog-v1 recommendation definitions (P1-E enrichment fields)."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RecDef:
    code: str
    title: str
    rationale_template: str
    effort: str  # S|M|L
    impact_base: float
    components: tuple[str, ...]
    visibility_relevant: bool = False
    # P1-E actionable enrichment (no ranking promises)
    problem: str = ""
    why_it_matters: str = ""
    recommended_action: str = ""
    implementation_pattern: str = ""
    validation_method: str = ""


EFFORT_WEIGHT = {"S": 1.0, "M": 0.7, "L": 0.4}

VISIBILITY_RELEVANT_CODES = frozenset(
    {
        "REC_IMPROVE_CITABLE_URLS",
        "REC_CLARIFY_BRAND_IN_COPY",
        "REC_ADD_FAQ_SECTION",
        "REC_ADD_JSONLD_ORG",
        "REC_ADD_ANSWER_FIRST",
    }
)


def _e(
    code: str,
    title: str,
    rationale: str,
    effort: str,
    impact: float,
    components: tuple[str, ...],
    *,
    visibility_relevant: bool = False,
    problem: str,
    why: str,
    action: str,
    pattern: str,
    validation: str,
) -> RecDef:
    return RecDef(
        code,
        title,
        rationale,
        effort,
        impact,
        components,
        visibility_relevant,
        problem,
        why,
        action,
        pattern,
        validation,
    )


REC_CATALOG: dict[str, RecDef] = {
    "REC_FIX_HOME_HTTP": _e(
        "REC_FIX_HOME_HTTP",
        "Fix homepage HTTP status",
        "Homepage did not return 200/203; answer engines cannot reliably fetch the primary URL.",
        "S",
        0.95,
        ("technical",),
        problem="Homepage HTTP status is not 200/203.",
        why="Crawlers and fetchers cannot use an unreachable primary URL as a citable source.",
        action="Restore a successful HTTP response for the canonical homepage URL.",
        pattern="Fix hosting/DNS/redirect loops; ensure the preferred URL returns 200 with HTML.",
        validation="Re-crawl homepage and confirm technical check T1 passes.",
    ),
    "REC_FIX_ROBOTS_BLOCK": _e(
        "REC_FIX_ROBOTS_BLOCK",
        "Allow AEOBot (and similar) in robots.txt",
        "robots.txt appears to disallow crawling of the site root for the analysis user-agent.",
        "S",
        0.95,
        ("technical",),
        problem="robots.txt disallows the analysis user-agent at site root.",
        why="Blocked crawl paths prevent readiness analysis and may block legitimate fetchers.",
        action="Update robots.txt Allow rules for AEOBot (and review AI search-index bots separately).",
        pattern="User-agent: AEOBot\\nAllow: /",
        validation="Fetch /robots.txt and confirm T2/AI crawler path policies show allow (accessibility only).",
    ),
    "REC_REMOVE_NOINDEX": _e(
        "REC_REMOVE_NOINDEX",
        "Remove noindex from homepage",
        "Homepage robots meta includes noindex, which blocks indexing and citation surfaces.",
        "S",
        0.90,
        ("technical",),
        problem="Homepage robots meta includes noindex.",
        why="noindex instructs indexers not to include the page in search/index surfaces.",
        action="Remove noindex from homepage meta robots unless intentionally private.",
        pattern='<meta name="robots" content="index,follow">',
        validation="Confirm T3 passes and homepage robots meta no longer contains noindex.",
    ),
    "REC_ADD_CANONICAL": _e(
        "REC_ADD_CANONICAL",
        "Add a same-host canonical URL on the homepage",
        "A clear canonical helps consolidating signals for the preferred URL.",
        "S",
        0.55,
        ("technical",),
        problem="Homepage lacks a same-host canonical URL.",
        why="Canonicals reduce duplicate-URL ambiguity for crawlers and citations.",
        action="Add a rel=canonical pointing at the preferred homepage URL on the same host.",
        pattern='<link rel="canonical" href="https://example.com/">',
        validation="Confirm T4 passes on re-analysis.",
    ),
    "REC_IMPROVE_TITLE": _e(
        "REC_IMPROVE_TITLE",
        "Improve homepage title length and clarity",
        "Title is missing or outside the 15–70 character guidance used in health-v1.",
        "S",
        0.50,
        ("technical",),
        problem="Homepage title missing or outside 15–70 characters.",
        why="Clear titles help entity recognition and snippet-style extraction.",
        action="Set a descriptive 15–70 character title including the primary brand.",
        pattern="<title>Brand — Primary offering</title>",
        validation="Confirm T5 is 1.0 after re-crawl.",
    ),
    "REC_ADD_META_DESCRIPTION": _e(
        "REC_ADD_META_DESCRIPTION",
        "Add a meta description",
        "Homepage lacks a meta description; short summaries help snippet and overview surfaces.",
        "S",
        0.40,
        ("technical",),
        problem="Homepage meta description missing or weak.",
        why="Short summaries aid human SERPs and some overview-style displays.",
        action="Add a 50–160 character meta description summarizing the offering.",
        pattern='<meta name="description" content="...">',
        validation="Confirm T6 improves on re-analysis.",
    ),
    "REC_REDUCE_JS_DEPENDENCY": _e(
        "REC_REDUCE_JS_DEPENDENCY",
        "Reduce JS-only content risk",
        "Body text is thin or inline script ratio is high; serve meaningful HTML without relying on scripts.",
        "L",
        0.85,
        ("technical", "content"),
        problem="High inline-script ratio or thin body text suggests JS-dependent content.",
        why="Many crawlers and fetchers read HTML; critical claims should not require script execution.",
        action="Server-render primary copy and reduce inline script bulk on key pages.",
        pattern="SSR/static HTML for hero + FAQ; defer non-critical JS.",
        validation="Confirm T7 and visible word-count checks improve.",
    ),
    "REC_FIX_HEADING_HIERARCHY": _e(
        "REC_FIX_HEADING_HIERARCHY",
        "Fix heading hierarchy",
        "Multiple pages have missing/duplicate h1 or skipped heading levels, hurting extractability.",
        "M",
        0.60,
        ("content",),
        problem="Heading hierarchy issues (missing/duplicate h1 or level skips).",
        why="Clear headings map questions to passages for extractors.",
        action="Ensure one h1 per page and sequential heading levels.",
        pattern="h1 → h2 → h3 without skips; unique topical h1.",
        validation="Confirm C1 pass rate improves across crawled pages.",
    ),
    "REC_ADD_ANSWER_FIRST": _e(
        "REC_ADD_ANSWER_FIRST",
        "Lead the homepage with an answer-first paragraph",
        "Homepage lacks an early declarative answer block of sufficient length.",
        "M",
        0.70,
        ("content", "answerability"),
        visibility_relevant=True,
        problem="Homepage lacks an early declarative answer-first paragraph.",
        why="Early self-contained claims are easier to extract as citable passages.",
        action="Add a ≥40 character declarative summary near the top of main content.",
        pattern="First <p> states who you are and what you offer in one clear sentence.",
        validation="Confirm C2/answer-first check passes on homepage.",
    ),
    "REC_ADD_FAQ_SECTION": _e(
        "REC_ADD_FAQ_SECTION",
        "Add FAQ / Q&A sections",
        "Few pages show FAQ/Q&A shape; question-aligned passages improve answerability.",
        "M",
        0.65,
        ("content", "answerability"),
        visibility_relevant=True,
        problem="Low FAQ/Q&A density across the crawl.",
        why="Question-aligned passages map cleanly to user queries.",
        action="Add FAQ sections (and FAQPage JSON-LD where accurate) on key pages.",
        pattern="h2 question? + answer paragraph; optional FAQPage schema.",
        validation="Confirm C3/A4 improve; re-check answerability score.",
    ),
    "REC_EXPAND_THIN_CONTENT": _e(
        "REC_EXPAND_THIN_CONTENT",
        "Expand thin pages",
        "Multiple pages fall below recommended visible word-count ranges.",
        "M",
        0.55,
        ("content",),
        problem="One or more pages are below recommended visible word-count ranges.",
        why="Very thin pages rarely contain extractable, self-contained claims.",
        action="Expand thin pages with substantive, unique explanations (not boilerplate).",
        pattern="Target ~300+ visible words on commercial/product pages where appropriate.",
        validation="Confirm C5 improves on previously thin URLs.",
    ),
    "REC_CONSOLIDATE_BRAND_NAME": _e(
        "REC_CONSOLIDATE_BRAND_NAME",
        "Consolidate brand naming across titles",
        "Brand token consistency is weak or titles diverge, reducing entity clarity.",
        "M",
        0.70,
        ("entity",),
        problem="Inconsistent brand strings across titles/pages.",
        why="Divergent names weaken entity clarity for models and extractors.",
        action="Pick one preferred brand spelling and use it consistently in titles and Organization schema.",
        pattern="Same brand token in <title>, og:site_name, and JSON-LD name.",
        validation="Confirm E1/E4 improve on re-analysis.",
    ),
    "REC_ADD_ORG_SIGNAL": _e(
        "REC_ADD_ORG_SIGNAL",
        "Add a clear Organization signal",
        "No strong Organization JSON-LD or footer identity was detected.",
        "S",
        0.75,
        ("entity",),
        problem="Missing clear Organization identity signal.",
        why="Organization markup/footer identity helps disambiguate the brand entity.",
        action="Add Organization JSON-LD and/or a clear footer copyright/org name.",
        pattern='JSON-LD @type Organization with name + url.',
        validation="Confirm E2 passes.",
    ),
    "REC_ADD_CONTACT_OR_SAMEAS": _e(
        "REC_ADD_CONTACT_OR_SAMEAS",
        "Add contact or sameAs links",
        "Contact mailto/path or schema.org sameAs was not found on homepage/about.",
        "S",
        0.45,
        ("entity",),
        problem="No contact mailto/path or sameAs links found.",
        why="sameAs/contact links strengthen entity graph connections.",
        action="Add sameAs profiles and a visible contact method on homepage or about.",
        pattern='Organization.sameAs: ["https://..."] + mailto: or /contact.',
        validation="Confirm E3 passes.",
    ),
    "REC_ADD_JSONLD_ORG": _e(
        "REC_ADD_JSONLD_ORG",
        "Add Organization JSON-LD on the homepage",
        "No parseable Organization node was found; entity clarity and structured data scores are limited by missing machine-readable identity.",
        "S",
        0.80,
        ("structured_data", "entity"),
        visibility_relevant=True,
        problem="No parseable Organization JSON-LD on the homepage.",
        why="Machine-readable identity helps structured understanding; it does not guarantee AI ranking.",
        action="Publish valid Organization JSON-LD on the homepage.",
        pattern='{"@context":"https://schema.org","@type":"Organization","name":"...","url":"..."}',
        validation="Confirm S1/S3/E2 and JSON-LD parse without SD_PARSE_ERROR.",
    ),
    "REC_BROADEN_JSONLD_COVERAGE": _e(
        "REC_BROADEN_JSONLD_COVERAGE",
        "Broaden JSON-LD coverage across key pages",
        "Fewer than 40% of successful pages expose parseable JSON-LD.",
        "M",
        0.55,
        ("structured_data",),
        problem="Low share of pages with parseable JSON-LD.",
        why="Sparse structured data limits machine-readable page typing.",
        action="Add appropriate JSON-LD on key templates (WebPage, Article, FAQPage, Product).",
        pattern="Template-level JSON-LD for each major page type.",
        validation="Confirm S2 coverage threshold improves.",
    ),
    "REC_ADD_TYPE_FIT_SCHEMA": _e(
        "REC_ADD_TYPE_FIT_SCHEMA",
        "Add well-known schema types",
        "No Organization/WebSite/Article/FAQPage/HowTo (etc.) types were detected site-wide.",
        "M",
        0.60,
        ("structured_data",),
        problem="No well-known schema.org types detected site-wide.",
        why="Recognized types help classify pages for extraction pipelines.",
        action="Add at least one fitting type (Organization, WebSite, FAQPage, HowTo, Article, Product).",
        pattern="Choose types that accurately describe the page; avoid spammy markup.",
        validation="Confirm S3 passes.",
    ),
    "REC_FIX_JSONLD_PARSE": _e(
        "REC_FIX_JSONLD_PARSE",
        "Fix invalid JSON-LD",
        "One or more JSON-LD blocks failed to parse; invalid structured data cannot be used.",
        "S",
        0.70,
        ("structured_data",),
        problem="Invalid JSON-LD blocks failed to parse.",
        why="Unparseable structured data is ignored by consumers of the markup.",
        action="Fix JSON syntax/escaping in script type=application/ld+json blocks.",
        pattern="Validate JSON; ensure one valid object/array per script tag.",
        validation="No SD_PARSE_ERROR evidence on re-crawl.",
    ),
    "REC_ADD_HOWTO_OR_STEPS": _e(
        "REC_ADD_HOWTO_OR_STEPS",
        "Add HowTo or step-by-step lists",
        "No ordered steps (≥3) or HowTo JSON-LD was found.",
        "M",
        0.50,
        ("answerability",),
        problem="No HowTo schema or ≥3-step ordered lists detected.",
        why="Step lists are highly extractable for procedural queries.",
        action="Add an accurate ordered list or HowTo JSON-LD on a relevant guide page.",
        pattern="<ol> with ≥3 steps or HowTo JSON-LD.",
        validation="Confirm A2 passes.",
    ),
    "REC_ADD_QUESTION_HEADINGS": _e(
        "REC_ADD_QUESTION_HEADINGS",
        "Add question-style headings",
        "No question headings were detected; Q-shaped headings help map queries to passages.",
        "S",
        0.45,
        ("answerability",),
        problem="No question-style headings detected.",
        why="Question headings map user queries to answer passages.",
        action="Add a few genuine who/what/how headings with direct answers beneath.",
        pattern="<h2>How does X work?</h2><p>…</p>",
        validation="Confirm A3 improves.",
    ),
    "REC_IMPROVE_CITABLE_URLS": _e(
        "REC_IMPROVE_CITABLE_URLS",
        "Publish stable, citable URLs in content",
        "Sample LLM URL-mention rate is low; ensure key pages have clear URLs and are referenced in authoritative copy.",
        "M",
        0.50,
        ("visibility",),
        visibility_relevant=True,
        problem="Sample llm_url_mention_rate is low under llm-mention-v1.",
        why="Stable public URLs make it easier for answers to reference your pages; this is not a ranking guarantee.",
        action="Publish durable URLs for key claims and reference them in authoritative on-site copy.",
        pattern="Canonical article/docs URLs linked from homepage and about.",
        validation="Re-run llm_mention experiment; treat URL-mention rate as a sample estimate only.",
    ),
    "REC_CLARIFY_BRAND_IN_COPY": _e(
        "REC_CLARIFY_BRAND_IN_COPY",
        "Clarify brand naming in on-page copy",
        "Sample LLM mention rate is low and entity signals are weak; use the preferred brand string consistently.",
        "M",
        0.55,
        ("visibility", "entity"),
        visibility_relevant=True,
        problem="Low sample llm_mention_rate with weak entity signals.",
        why="Consistent brand strings improve recognition in text; not a ChatGPT ranking promise.",
        action="Use the preferred brand spelling consistently in titles, lead paragraphs, and Organization schema.",
        pattern="Brand in h1/lead + JSON-LD name match.",
        validation="Re-run llm_mention experiment and entity checks; interpret as sample estimates.",
    ),
    "REC_REVIEW_DEMO_ONLY": _e(
        "REC_REVIEW_DEMO_ONLY",
        "Re-run with live credentials when ready",
        "This job used DemoProvider because live credentials were unavailable; visibility rates are synthetic.",
        "S",
        0.20,
        ("meta",),
        problem="Visibility observations are synthetic_demo.",
        why="Demo fixtures are for product demonstration, not live visibility measurement.",
        action="Re-run with OPENAI_API_KEY (llm_mention) or a retrieval-enabled provider when measuring live signals.",
        pattern="Set credentials; provider=openai_compatible or auto.",
        validation="Confirm experiment provenance is api_observation and experiment_kind is labeled correctly.",
    ),
}
